// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { existsSync } from "fs";
import { defineConfig } from "prisma/config";

dotenv.config();
if (existsSync(".env.development")) {
  dotenv.config({ path: ".env.development", override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["FM_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
